version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: challenge_db
      MYSQL_USER: challuser
      MYSQL_PASSWORD: challpass
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "3306:3306"
  app:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: challuser
      DB_PASSWORD: challpass
      DB_NAME: challenge_db
    ports:
      - "5000:5000"
